@ECHO OFF
start %~dp0%/t1/run.bat
start %~dp0%/t2/run.bat
start %~dp0%/t3/run.bat
start %~dp0%/t4/run.bat
start %~dp0%/t5/run.bat
start %~dp0%/t6/run.bat
start %~dp0%/t7/run.bat
start %~dp0%/t8/run.bat
start %~dp0%/t9/run.bat
start %~dp0%/t10/run.bat